In [ ]:
import pandas as pd
data=pd.read_excel("/content/Excel.xlsl.xlsx")
data

,Unnamed: 0,Student_ID,Name,Age,Gender,Course,Marks,City,Admission_Date
0,0,S201,Rahul,20.0,Male,BCA,85.0,Bengaluru,2023-12-06 00:00:00
1,1,S202,Priya,NaN,Female,BBA,78.0,Chennai,15-07-2023
2,2,S203,Arjun,21.0,Male,BCA,92.0,Hyderabad,2023-10-08 00:00:00
3,3,S204,Sneha,19.0,Female,MCA,88.0,Mysuru,20-06-2023
4,4,S205,Kiran,150.0,Male,BBA,65.0,Bengaluru,2023-10-07 00:00:00
5,5,S206,Anjali,22.0,Female,BCA,-45.0,Chennai,15-07-2023
6,6,S207,Ravi,21.0,Male,MCA,95.0,Delhi,2023-01-08 00:00:00
7,7,S208,NaN,20.0,Female,BCA,72.0,Hyderabad,22-08-2023
8,8,S209,Manju,-19.0,Female,BBA,80.0,Bengaluru,2023-10-07 00:00:00
9,9,S210,Suresh,22.0,Male,MCA,89.0,Chennai,2023-05-08 00:00:00
10,10,S201,Rahul,20.0,Male,BCA,85.0,Bengaluru,2023-12-06 00:00:00
11,11,S212,Divya,21.0,Female,NaN,76.0,Mysuru,18-07-2023
12,12,S213,Naveen,22.0,Male,BCA,NaN,Hyderabad,25-08-2023
13,13,S214,Pooja,20.0,Female,BBA,68.0,NaN,2023-12-07 00:00:00
14,14,S215,Mahesh,23.0,Male,MCA,NaN,Bengaluru,30-06-2023

In [ ]:
data.isnull()

,Unnamed: 0,Student_ID,Name,Age,Gender,Course,Marks,City,Admission_Date
0,False,False,False,False,False,False,False,False,False
1,False,False,False,True,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False
7,False,False,True,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,True,False,False,False
12,False,False,False,False,False,False,True,False,False
13,False,False,False,False,False,False,False,True,False
14,False,False,False,False,False,False,True,False,False

In [ ]:
import numpy as np
data.loc[data['Age']>90,'Age']=np.nan
data

,Unnamed: 0,Student_ID,Name,Age,Gender,Course,Marks,City,Admission_Date
0,0,S201,Rahul,20.0,Male,BCA,85.0,Bengaluru,2023-12-06 00:00:00
1,1,S202,Priya,NaN,Female,BBA,78.0,Chennai,15-07-2023
2,2,S203,Arjun,21.0,Male,BCA,92.0,Hyderabad,2023-10-08 00:00:00
3,3,S204,Sneha,19.0,Female,MCA,88.0,Mysuru,20-06-2023
4,4,S205,Kiran,NaN,Male,BBA,65.0,Bengaluru,2023-10-07 00:00:00
5,5,S206,Anjali,22.0,Female,BCA,-45.0,Chennai,15-07-2023
6,6,S207,Ravi,21.0,Male,MCA,95.0,Delhi,2023-01-08 00:00:00
7,7,S208,NaN,20.0,Female,BCA,72.0,Hyderabad,22-08-2023
8,8,S209,Manju,-19.0,Female,BBA,80.0,Bengaluru,2023-10-07 00:00:00
9,9,S210,Suresh,22.0,Male,MCA,89.0,Chennai,2023-05-08 00:00:00
10,10,S201,Rahul,20.0,Male,BCA,85.0,Bengaluru,2023-12-06 00:00:00
11,11,S212,Divya,21.0,Female,NaN,76.0,Mysuru,18-07-2023
12,12,S213,Naveen,22.0,Male,BCA,NaN,Hyderabad,25-08-2023
13,13,S214,Pooja,20.0,Female,BBA,68.0,NaN,2023-12-07 00:00:00
14,14,S215,Mahesh,23.0,Male,MCA,NaN,Bengaluru,30-06-2023

In [ ]:
data['Age']=data['Age'].fillna(data['Age'].mean())
data

,Unnamed: 0,Student_ID,Name,Age,Gender,Course,Marks,City,Admission_Date
0,0,S201,Rahul,20.000000,Male,BCA,85.0,Bengaluru,2023-12-06 00:00:00
1,1,S202,Priya,17.846154,Female,BBA,78.0,Chennai,15-07-2023
2,2,S203,Arjun,21.000000,Male,BCA,92.0,Hyderabad,2023-10-08 00:00:00
3,3,S204,Sneha,19.000000,Female,MCA,88.0,Mysuru,20-06-2023
4,4,S205,Kiran,17.846154,Male,BBA,65.0,Bengaluru,2023-10-07 00:00:00
5,5,S206,Anjali,22.000000,Female,BCA,-45.0,Chennai,15-07-2023
6,6,S207,Ravi,21.000000,Male,MCA,95.0,Delhi,2023-01-08 00:00:00
7,7,S208,NaN,20.000000,Female,BCA,72.0,Hyderabad,22-08-2023
8,8,S209,Manju,-19.000000,Female,BBA,80.0,Bengaluru,2023-10-07 00:00:00
9,9,S210,Suresh,22.000000,Male,MCA,89.0,Chennai,2023-05-08 00:00:00
10,10,S201,Rahul,20.000000,Male,BCA,85.0,Bengaluru,2023-12-06 00:00:00
11,11,S212,Divya,21.000000,Female,NaN,76.0,Mysuru,18-07-2023
12,12,S213,Naveen,22.000000,Male,BCA,NaN,Hyderabad,25-08-2023
13,13,S214,Pooja,20.000000,Female,BBA,68.0,NaN,2023-12-07 00:00:00
14,14,S215,Mahesh,23.000000,Male,MCA,NaN,Bengaluru,30-06-2023

In [ ]:
data.dtypes

Unnamed: 0          int64
Student_ID         object
Name               object
Age               float64
Gender             object
Course             object
Marks             float64
City               object
Admission_Date     object
dtype: object

In [ ]:
data['Age']=data['Age'].astype(int)
data

,Unnamed: 0,Student_ID,Name,Age,Gender,Course,Marks,City,Admission_Date
0,0,S201,Rahul,20,Male,BCA,85.0,Bengaluru,2023-12-06 00:00:00
1,1,S202,Priya,17,Female,BBA,78.0,Chennai,15-07-2023
2,2,S203,Arjun,21,Male,BCA,92.0,Hyderabad,2023-10-08 00:00:00
3,3,S204,Sneha,19,Female,MCA,88.0,Mysuru,20-06-2023
4,4,S205,Kiran,17,Male,BBA,65.0,Bengaluru,2023-10-07 00:00:00
5,5,S206,Anjali,22,Female,BCA,-45.0,Chennai,15-07-2023
6,6,S207,Ravi,21,Male,MCA,95.0,Delhi,2023-01-08 00:00:00
7,7,S208,NaN,20,Female,BCA,72.0,Hyderabad,22-08-2023
8,8,S209,Manju,-19,Female,BBA,80.0,Bengaluru,2023-10-07 00:00:00
9,9,S210,Suresh,22,Male,MCA,89.0,Chennai,2023-05-08 00:00:00
10,10,S201,Rahul,20,Male,BCA,85.0,Bengaluru,2023-12-06 00:00:00
11,11,S212,Divya,21,Female,NaN,76.0,Mysuru,18-07-2023
12,12,S213,Naveen,22,Male,BCA,NaN,Hyderabad,25-08-2023
13,13,S214,Pooja,20,Female,BBA,68.0,NaN,2023-12-07 00:00:00
14,14,S215,Mahesh,23,Male,MCA,NaN,Bengaluru,30-06-2023

In [ ]:
data.dtypes

Unnamed: 0          int64
Student_ID         object
Name               object
Age                 int64
Gender             object
Course             object
Marks             float64
City               object
Admission_Date     object
dtype: object

In [ ]:
data['Gender']=data['Gender'].replace({"M":"Male","F":"Female"})
data

,Unnamed: 0,Student_ID,Name,Age,Gender,Course,Marks,City,Admission_Date
0,0,S201,Rahul,20,Male,BCA,85.0,Bengaluru,2023-12-06 00:00:00
1,1,S202,Priya,17,Female,BBA,78.0,Chennai,15-07-2023
2,2,S203,Arjun,21,Male,BCA,92.0,Hyderabad,2023-10-08 00:00:00
3,3,S204,Sneha,19,Female,MCA,88.0,Mysuru,20-06-2023
4,4,S205,Kiran,17,Male,BBA,65.0,Bengaluru,2023-10-07 00:00:00
5,5,S206,Anjali,22,Female,BCA,-45.0,Chennai,15-07-2023
6,6,S207,Ravi,21,Male,MCA,95.0,Delhi,2023-01-08 00:00:00
7,7,S208,NaN,20,Female,BCA,72.0,Hyderabad,22-08-2023
8,8,S209,Manju,-19,Female,BBA,80.0,Bengaluru,2023-10-07 00:00:00
9,9,S210,Suresh,22,Male,MCA,89.0,Chennai,2023-05-08 00:00:00
10,10,S201,Rahul,20,Male,BCA,85.0,Bengaluru,2023-12-06 00:00:00
11,11,S212,Divya,21,Female,NaN,76.0,Mysuru,18-07-2023
12,12,S213,Naveen,22,Male,BCA,NaN,Hyderabad,25-08-2023
13,13,S214,Pooja,20,Female,BBA,68.0,NaN,2023-12-07 00:00:00
14,14,S215,Mahesh,23,Male,MCA,NaN,Bengaluru,30-06-2023

In [ ]:
data=pd.get_dummies(data,columns=['Gender'],dtype=int)
data

,Unnamed: 0,Student_ID,Name,Age,Course,Marks,City,Admission_Date,Gender_ Female,Gender_Female,Gender_Male
0,0,S201,Rahul,20,BCA,85.0,Bengaluru,2023-12-06 00:00:00,0,0,1
1,1,S202,Priya,17,BBA,78.0,Chennai,15-07-2023,0,1,0
2,2,S203,Arjun,21,BCA,92.0,Hyderabad,2023-10-08 00:00:00,0,0,1
3,3,S204,Sneha,19,MCA,88.0,Mysuru,20-06-2023,0,1,0
4,4,S205,Kiran,17,BBA,65.0,Bengaluru,2023-10-07 00:00:00,0,0,1
5,5,S206,Anjali,22,BCA,-45.0,Chennai,15-07-2023,0,1,0
6,6,S207,Ravi,21,MCA,95.0,Delhi,2023-01-08 00:00:00,0,0,1
7,7,S208,NaN,20,BCA,72.0,Hyderabad,22-08-2023,0,1,0
8,8,S209,Manju,-19,BBA,80.0,Bengaluru,2023-10-07 00:00:00,0,1,0
9,9,S210,Suresh,22,MCA,89.0,Chennai,2023-05-08 00:00:00,0,0,1
10,10,S201,Rahul,20,BCA,85.0,Bengaluru,2023-12-06 00:00:00,0,0,1
11,11,S212,Divya,21,NaN,76.0,Mysuru,18-07-2023,0,1,0
12,12,S213,Naveen,22,BCA,NaN,Hyderabad,25-08-2023,0,0,1
13,13,S214,Pooja,20,BBA,68.0,NaN,2023-12-07 00:00:00,1,0,0
14,14,S215,Mahesh,23,MCA,NaN,Bengaluru,30-06-2023,0,0,1

In [ ]:
import pandas as pd
data=pd.read_excel("/content/Student.xlsx")
data

,Student_ID,Name,Age,Gender,Course,Marks,City,Admission_Date
0,S201,Rahul,20.0,M,BCA,85.0,Bengaluru,2023-12-06 00:00:00
1,S202,Priya,NaN,Female,BBA,78.0,Chennai,15-07-2023
2,S203,Arjun,21.0,Male,BCA,92.0,Hyderabad,2023-10-08 00:00:00
3,S204,Sneha,19.0,F,MCA,88.0,Mysuru,20-06-2023
4,S205,Kiran,150.0,Male,BBA,65.0,Bengaluru,2023-10-07 00:00:00
5,S206,Anjali,22.0,Female,BCA,-45.0,Chennai,15-07-2023
6,NaN,Ravi,21.0,M,MCA,95.0,Delhi,2023-01-08 00:00:00
7,S208,NaN,20.0,Female,BCA,72.0,Hyderabad,22-08-2023
8,S209,Manju,-19.0,F,BBA,80.0,Bengaluru,2023-10-07 00:00:00
9,S210,Suresh,22.0,Male,MCA,89.0,Chennai,2023-05-08 00:00:00
10,S201,Rahul,20.0,M,BCA,85.0,Bengaluru,2023-12-06 00:00:00
11,S212,Divya,21.0,Female,NaN,76.0,Mysuru,18-07-2023
12,S213,Naveen,22.0,Male,BCA,NaN,Hyderabad,25-08-2023
13,S214,Pooja,20.0,Female,BBA,68.0,NaN,2023-12-07 00:00:00
14,S215,Mahesh,23.0,Male,MCA,105.0,Bengaluru,30-06-2023

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Student_ID      14 non-null     object
 1   Name            14 non-null     object
 2   Age             14 non-null     float64
 3   Gender          15 non-null     object
 4   Course          14 non-null     object
 5   Marks           14 non-null     float64
 6   City            14 non-null     object
 7   Admission_Date  15 non-null     object
dtypes: float64(2), object(6)
memory usage: 1.1+ KB

In [ ]:
data.dtypes

Student_ID         object
Name               object
Age               float64
Gender             object
Course             object
Marks             float64
City               object
Admission_Date     object
dtype: object

In [ ]:
data.head()

,Student_ID,Name,Age,Gender,Course,Marks,City,Admission_Date
0,S201,Rahul,20.0,M,BCA,85.0,Bengaluru,2023-12-06 00:00:00
1,S202,Priya,NaN,Female,BBA,78.0,Chennai,15-07-2023
2,S203,Arjun,21.0,Male,BCA,92.0,Hyderabad,2023-10-08 00:00:00
3,S204,Sneha,19.0,F,MCA,88.0,Mysuru,20-06-2023
4,S205,Kiran,150.0,Male,BBA,65.0,Bengaluru,2023-10-07 00:00:00

In [ ]:
data.tail()

,Student_ID,Name,Age,Gender,Course,Marks,City,Admission_Date
10,S201,Rahul,20.0,M,BCA,85.0,Bengaluru,2023-12-06 00:00:00
11,S212,Divya,21.0,Female,NaN,76.0,Mysuru,18-07-2023
12,S213,Naveen,22.0,Male,BCA,NaN,Hyderabad,25-08-2023
13,S214,Pooja,20.0,Female,BBA,68.0,NaN,2023-12-07 00:00:00
14,S215,Mahesh,23.0,Male,MCA,105.0,Bengaluru,30-06-2023

In [ ]:
data.isnull()

    Student_ID   Name    Age  Gender  Course  Marks   City  Admission_Date
0        False  False  False   False   False  False  False           False
1        False  False   True   False   False  False  False           False
2        False  False  False   False   False  False  False           False
3        False  False  False   False   False  False  False           False
4        False  False  False   False   False  False  False           False
5        False  False  False   False   False  False  False           False
6         True  False  False   False   False  False  False           False
7        False   True  False   False   False  False  False           False
8        False  False  False   False   False  False  False           False
9        False  False  False   False   False  False  False           False
10       False  False  False   False   False  False  False           False
11       False  False  False   False    True  False  False           False
12       False  False  False   False   False   True  False           False
13       False  False  False   False   False  False   True           False
14       False  False  False   False   False  False  False           False

In [ ]:
data.isnull().sum()

Student_ID        1
Name              1
Age               1
Gender            0
Course            1
Marks             1
City              1
Admission_Date    0
dtype: int64

In [ ]:
data.isnull().sum().sum()

np.int64(6)

In [ ]:
data.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11    False
12    False
13    False
14    False
dtype: bool

In [ ]:
data.duplicated().sum()

np.int64(1)

In [ ]:
data.drop_duplicates()

,Student_ID,Name,Age,Gender,Course,Marks,City,Admission_Date
0,S201,Rahul,20.0,M,BCA,85.0,Bengaluru,2023-12-06 00:00:00
1,S202,Priya,NaN,Female,BBA,78.0,Chennai,15-07-2023
2,S203,Arjun,21.0,Male,BCA,92.0,Hyderabad,2023-10-08 00:00:00
3,S204,Sneha,19.0,F,MCA,88.0,Mysuru,20-06-2023
4,S205,Kiran,150.0,Male,BBA,65.0,Bengaluru,2023-10-07 00:00:00
5,S206,Anjali,22.0,Female,BCA,-45.0,Chennai,15-07-2023
6,NaN,Ravi,21.0,M,MCA,95.0,Delhi,2023-01-08 00:00:00
7,S208,NaN,20.0,Female,BCA,72.0,Hyderabad,22-08-2023
8,S209,Manju,-19.0,F,BBA,80.0,Bengaluru,2023-10-07 00:00:00
9,S210,Suresh,22.0,Male,MCA,89.0,Chennai,2023-05-08 00:00:00
11,S212,Divya,21.0,Female,NaN,76.0,Mysuru,18-07-2023
12,S213,Naveen,22.0,Male,BCA,NaN,Hyderabad,25-08-2023
13,S214,Pooja,20.0,Female,BBA,68.0,NaN,2023-12-07 00:00:00
14,S215,Mahesh,23.0,Male,MCA,105.0,Bengaluru,30-06-2023

In [ ]:
data['Student_ID']=data['Student_ID'].fillna('S207')
data

   Student_ID     Name   Age     Gender Course  Marks       City
0        S201    Rahul    20       Male    BCA   85.0  Bengaluru
1        S202    Priya  <NA>     Female    BBA   78.0    Chennai
2        S203    Arjun    21       Male    BCA   92.0  Hyderabad
3        S204    Sneha    19     Female    MCA   88.0     Mysuru
4        S205    Kiran   150       Male    BBA   65.0  Bengaluru
5        S206   Anjali    22     Female    BCA  -45.0    Chennai
6        S207     Ravi    21       Male    MCA   95.0      Delhi
7        S208      NaN    20     Female    BCA   72.0  Hyderabad
8        S209    Manju   -19     Female    BBA   80.0  Bengaluru
9        S210   Suresh    22       Male    MCA   89.0    Chennai
10       S201    Rahul    20       Male    BCA   85.0  Bengaluru
11       S212    Divya    21     Female    NaN   76.0     Mysuru
12       S213   Naveen    22       Male    BCA    NaN  Hyderabad
13       S214    Pooja    20     Female    BBA   68.0        NaN
14       S215   Mahesh    23       Male    MCA    NaN  Bengaluru

In [ ]:
data.loc[data['Marks']>100,'Marks']=np.nan
data

   Student_ID     Name   Age     Gender Course  Marks       City
0        S201    Rahul    20       Male    BCA   85.0  Bengaluru
1        S202    Priya  <NA>     Female    BBA   78.0    Chennai
2        S203    Arjun    21       Male    BCA   92.0  Hyderabad
3        S204    Sneha    19     Female    MCA   88.0     Mysuru
4        S205    Kiran   150       Male    BBA   65.0  Bengaluru
5        S206   Anjali    22     Female    BCA  -45.0    Chennai
6        S207     Ravi    21       Male    MCA   95.0      Delhi
7        S208      NaN    20     Female    BCA   72.0  Hyderabad
8        S209    Manju   -19     Female    BBA   80.0  Bengaluru
9        S210   Suresh    22       Male    MCA   89.0    Chennai
10       S201    Rahul    20       Male    BCA   85.0  Bengaluru
11       S212    Divya    21     Female    NaN   76.0     Mysuru
12       S213   Naveen    22       Male    BCA    NaN  Hyderabad
13       S214    Pooja    20     Female    BBA   68.0        NaN
14       S215   Mahesh    23       Male    MCA    NaN  Bengaluru

In [ ]:
data['Gender']=data['Gender'].replace({"M":"Male","F":"Female"})
data

,Student_ID,Name,Age,Gender,Course,Marks,City,Admission_Date
0,S201,Rahul,20.0,Male,BCA,85.0,Bengaluru,2023-12-06 00:00:00
1,S202,Priya,NaN,Female,BBA,78.0,Chennai,15-07-2023
2,S203,Arjun,21.0,Male,BCA,92.0,Hyderabad,2023-10-08 00:00:00
3,S204,Sneha,19.0,Female,MCA,88.0,Mysuru,20-06-2023
4,S205,Kiran,150.0,Male,BBA,65.0,Bengaluru,2023-10-07 00:00:00
5,S206,Anjali,22.0,Female,BCA,-45.0,Chennai,15-07-2023
6,S207,Ravi,21.0,Male,MCA,95.0,Delhi,2023-01-08 00:00:00
7,S208,NaN,20.0,Female,BCA,72.0,Hyderabad,22-08-2023
8,S209,Manju,-19.0,Female,BBA,80.0,Bengaluru,2023-10-07 00:00:00
9,S210,Suresh,22.0,Male,MCA,89.0,Chennai,2023-05-08 00:00:00
10,S201,Rahul,20.0,Male,BCA,85.0,Bengaluru,2023-12-06 00:00:00
11,S212,Divya,21.0,Female,NaN,76.0,Mysuru,18-07-2023
12,S213,Naveen,22.0,Male,BCA,NaN,Hyderabad,25-08-2023
13,S214,Pooja,20.0,Female,BBA,68.0,NaN,2023-12-07 00:00:00
14,S215,Mahesh,23.0,Male,MCA,NaN,Bengaluru,30-06-2023

In [ ]:
data['Age']=data['Age'].astype('Int64')
data

,Student_ID,Name,Age,Gender,Course,Marks,City,Admission_Date
0,S201,Rahul,20,Male,BCA,85.0,Bengaluru,2023-12-06 00:00:00
1,S202,Priya,<NA>,Female,BBA,78.0,Chennai,15-07-2023
2,S203,Arjun,21,Male,BCA,92.0,Hyderabad,2023-10-08 00:00:00
3,S204,Sneha,19,Female,MCA,88.0,Mysuru,20-06-2023
4,S205,Kiran,150,Male,BBA,65.0,Bengaluru,2023-10-07 00:00:00
5,S206,Anjali,22,Female,BCA,-45.0,Chennai,15-07-2023
6,S207,Ravi,21,Male,MCA,95.0,Delhi,2023-01-08 00:00:00
7,S208,NaN,20,Female,BCA,72.0,Hyderabad,22-08-2023
8,S209,Manju,-19,Female,BBA,80.0,Bengaluru,2023-10-07 00:00:00
9,S210,Suresh,22,Male,MCA,89.0,Chennai,2023-05-08 00:00:00
10,S201,Rahul,20,Male,BCA,85.0,Bengaluru,2023-12-06 00:00:00
11,S212,Divya,21,Female,NaN,76.0,Mysuru,18-07-2023
12,S213,Naveen,22,Male,BCA,NaN,Hyderabad,25-08-2023
13,S214,Pooja,20,Female,BBA,68.0,NaN,2023-12-07 00:00:00
14,S215,Mahesh,23,Male,MCA,NaN,Bengaluru,30-06-2023

In [ ]:
data.describe()

             Age      Marks
count       14.0  13.000000
mean   27.285714  71.384615
std    36.902009  36.144475
min        -19.0 -45.000000
25%         20.0  72.000000
50%         21.0  80.000000
75%         22.0  88.000000
max        150.0  95.000000

In [ ]:
data['City']=data['City'].str.strip()
data

,Student_ID,Name,Age,Gender,Course,Marks,City,Admission_Date
0,S201,Rahul,20,Male,BCA,85.0,Bengaluru,2023-12-06 00:00:00
1,S202,Priya,<NA>,Female,BBA,78.0,Chennai,15-07-2023
2,S203,Arjun,21,Male,BCA,92.0,Hyderabad,2023-10-08 00:00:00
3,S204,Sneha,19,Female,MCA,88.0,Mysuru,20-06-2023
4,S205,Kiran,150,Male,BBA,65.0,Bengaluru,2023-10-07 00:00:00
5,S206,Anjali,22,Female,BCA,-45.0,Chennai,15-07-2023
6,S207,Ravi,21,Male,MCA,95.0,Delhi,2023-01-08 00:00:00
7,S208,NaN,20,Female,BCA,72.0,Hyderabad,22-08-2023
8,S209,Manju,-19,Female,BBA,80.0,Bengaluru,2023-10-07 00:00:00
9,S210,Suresh,22,Male,MCA,89.0,Chennai,2023-05-08 00:00:00
10,S201,Rahul,20,Male,BCA,85.0,Bengaluru,2023-12-06 00:00:00
11,S212,Divya,21,Female,NaN,76.0,Mysuru,18-07-2023
12,S213,Naveen,22,Male,BCA,NaN,Hyderabad,25-08-2023
13,S214,Pooja,20,Female,BBA,68.0,NaN,2023-12-07 00:00:00
14,S215,Mahesh,23,Male,MCA,NaN,Bengaluru,30-06-2023

In [ ]:
data.shape

(15, 8)

In [ ]:
data.columns

Index(['Student_ID', 'Name', 'Age', 'Gender', 'Course', 'Marks', 'City',
       'Admission_Date'],
      dtype='object')

In [ ]:
data.to_csv()

',Student_ID,Name,Age,Gender,Course,Marks,City,Admission_Date\n0,S201,Rahul,20,Male,BCA,85.0,Bengaluru,2023-12-06 00:00:00\n1,S202,Priya,,Female,BBA,78.0,Chennai,15-07-2023\n2,S203,Arjun,21,Male,BCA,92.0,Hyderabad,2023-10-08 00:00:00\n3,S204,Sneha,19,Female,MCA,88.0,Mysuru,20-06-2023\n4,S205,Kiran,150,Male,BBA,65.0,Bengaluru,2023-10-07 00:00:00\n5,S206,Anjali,22,Female,  BCA,-45.0,Chennai,15-07-2023\n6,S207,Ravi,21,Male,MCA,95.0,Delhi,2023-01-08 00:00:00\n7,S208,,20,Female,BCA,72.0,Hyderabad,22-08-2023\n8,S209,Manju,-19,Female,BBA,80.0,Bengaluru,2023-10-07 00:00:00\n9,S210,Suresh,22,Male,MCA,89.0,Chennai,2023-05-08 00:00:00\n10,S201,Rahul,20,Male,BCA,85.0,Bengaluru,2023-12-06 00:00:00\n11,S212,  Divya,21,Female,,76.0,Mysuru,18-07-2023\n12,S213,Naveen,22,Male,BCA,,Hyderabad,25-08-2023\n13,S214,Pooja,20,   Female,BBA,68.0,,2023-12-07 00:00:00\n14,S215,Mahesh,23,Male,MCA,,Bengaluru,30-06-2023\n'

In [ ]:
data.to_excel("/content/Excel.xlsl.xlsx")
data

,Student_ID,Name,Age,Gender,Course,Marks,City,Admission_Date
0,S201,Rahul,20,Male,BCA,85.0,Bengaluru,2023-12-06 00:00:00
1,S202,Priya,<NA>,Female,BBA,78.0,Chennai,15-07-2023
2,S203,Arjun,21,Male,BCA,92.0,Hyderabad,2023-10-08 00:00:00
3,S204,Sneha,19,Female,MCA,88.0,Mysuru,20-06-2023
4,S205,Kiran,150,Male,BBA,65.0,Bengaluru,2023-10-07 00:00:00
5,S206,Anjali,22,Female,BCA,-45.0,Chennai,15-07-2023
6,S207,Ravi,21,Male,MCA,95.0,Delhi,2023-01-08 00:00:00
7,S208,NaN,20,Female,BCA,72.0,Hyderabad,22-08-2023
8,S209,Manju,-19,Female,BBA,80.0,Bengaluru,2023-10-07 00:00:00
9,S210,Suresh,22,Male,MCA,89.0,Chennai,2023-05-08 00:00:00
10,S201,Rahul,20,Male,BCA,85.0,Bengaluru,2023-12-06 00:00:00
11,S212,Divya,21,Female,NaN,76.0,Mysuru,18-07-2023
12,S213,Naveen,22,Male,BCA,NaN,Hyderabad,25-08-2023
13,S214,Pooja,20,Female,BBA,68.0,NaN,2023-12-07 00:00:00
14,S215,Mahesh,23,Male,MCA,NaN,Bengaluru,30-06-2023

In [ ]:
data['Age'].mean()

np.float64(27.285714285714285)

In [ ]:
data['Marks'].mean()

np.float64(71.38461538461539)

In [ ]:
data=data.drop(['Admission_Date'],axis=1)
data

   Student_ID     Name   Age     Gender Course  Marks       City
0        S201    Rahul    20       Male    BCA   85.0  Bengaluru
1        S202    Priya  <NA>     Female    BBA   78.0    Chennai
2        S203    Arjun    21       Male    BCA   92.0  Hyderabad
3        S204    Sneha    19     Female    MCA   88.0     Mysuru
4        S205    Kiran   150       Male    BBA   65.0  Bengaluru
5        S206   Anjali    22     Female    BCA  -45.0    Chennai
6        S207     Ravi    21       Male    MCA   95.0      Delhi
7        S208      NaN    20     Female    BCA   72.0  Hyderabad
8        S209    Manju   -19     Female    BBA   80.0  Bengaluru
9        S210   Suresh    22       Male    MCA   89.0    Chennai
10       S201    Rahul    20       Male    BCA   85.0  Bengaluru
11       S212    Divya    21     Female    NaN   76.0     Mysuru
12       S213   Naveen    22       Male    BCA    NaN  Hyderabad
13       S214    Pooja    20     Female    BBA   68.0        NaN
14       S215   Mahesh    23       Male    MCA    NaN  Bengaluru

In [ ]:
data['Age'].max()

np.int64(150)

In [ ]:
data['Marks'].min()

-45.0

In [ ]:
data['Age'].min()

np.int64(-19)

In [ ]:
data['Marks'].max()

95.0

In [ ]:
data.shape

(15, 7)

In [ ]:
data['Marks'].median()

80.0

In [ ]:
print(data['Course'].unique())

['BCA' 'BBA' 'MCA' '  BCA' nan]

In [ ]:
print(data['Course'].value_counts())

Course
BCA      5
BBA      4
MCA      4
  BCA    1
Name: count, dtype: int64

In [ ]:
data['Marks'].mode()

0    85.0
Name: Marks, dtype: float64

In [ ]:
data.describe()

             Age      Marks
count       14.0  13.000000
mean   27.285714  71.384615
std    36.902009  36.144475
min        -19.0 -45.000000
25%         20.0  72.000000
50%         21.0  80.000000
75%         22.0  88.000000
max        150.0  95.000000

In [ ]:
data.interpolate()

/tmp/ipykernel_3591/982976692.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  data.interpolate()

   Student_ID     Name    Age     Gender Course  Marks       City
0        S201    Rahul   20.0       Male    BCA   85.0  Bengaluru
1        S202    Priya   20.5     Female    BBA   78.0    Chennai
2        S203    Arjun   21.0       Male    BCA   92.0  Hyderabad
3        S204    Sneha   19.0     Female    MCA   88.0     Mysuru
4        S205    Kiran  150.0       Male    BBA   65.0  Bengaluru
5        S206   Anjali   22.0     Female    BCA  -45.0    Chennai
6        S207     Ravi   21.0       Male    MCA   95.0      Delhi
7        S208      NaN   20.0     Female    BCA   72.0  Hyderabad
8        S209    Manju  -19.0     Female    BBA   80.0  Bengaluru
9        S210   Suresh   22.0       Male    MCA   89.0    Chennai
10       S201    Rahul   20.0       Male    BCA   85.0  Bengaluru
11       S212    Divya   21.0     Female    NaN   76.0     Mysuru
12       S213   Naveen   22.0       Male    BCA   72.0  Hyderabad
13       S214    Pooja   20.0     Female    BBA   68.0        NaN
14       S215   Mahesh   23.0       Male    MCA   68.0  Bengaluru