In [ ]:
import pandas as pd
data = pd.read_csv("/content/Emp.csv")
data

    id     Name  Salary     company
0  101     Ravi   20000         TCS
1  102    Prema   30000       Wipro
2  103     Basu   47000   Accenture
3  104   Prabhu  100000     Infosys

In [ ]:
import pandas as pd
data=pd.read_excel("/content/Teacher.xlsx")
data

        ID   Name       Department  Unnamed: 3    Salary
0      101  Rahul               IT         NaN     50000
1      102  Anita               HR         NaN     45000
2      103   John            Sales         NaN     65000
3      104  Kiran               IT         NaN     55000

In [ ]:
data['Name']

0    Rahul
1    Anita
2     John
3    Kiran
Name: Name, dtype: object

In [ ]:
import pandas as pd
data =pd.read_csv("/content/Emp.csv")
data

    id     Name  Salary     company
0  101     Ravi   20000         TCS
1  102    Prema   30000       Wipro
2  103     Basu   47000   Accenture
3  104   Prabhu  100000     Infosys

In [ ]:
data["Age"]=[20,21,22,28]
data

    id     Name   Salary     company  Age
0  101     Ravi    20000         TCS   20
1  102    Prema    30000       Wipro   21
2  103     Basu    47000   Accenture   22
3  104   Prabhu   100000     Infosys   28

In [ ]:
data["Age"]=[20,21,22,18]
data.to_csv('Age',index=False)
data

    id     Name   Salary     company  Age
0  101     Ravi    20000         TCS   20
1  102    Prema    30000       Wipro   21
2  103     Basu    47000   Accenture   22
3  104   Prabhu   100000     Infosys   18

In [ ]:
data['City']=['Gadag','Yadagiri','Hallikeri','Mysore']
data.to_csv('City',index=False)
data

    id     Name   Salary     company  Age       City
0  101     Ravi    20000         TCS   20      Gadag
1  102    Prema    30000       Wipro   21   Yadagiri
2  103     Basu    47000   Accenture   22  Hallikeri
3  104   Prabhu   100000     Infosys   18     Mysore

In [ ]:
data['Age']=[20,21,22,18]
data.to_csv('Age',index=False)
data

    id     Name   Salary     company  Age
0  101     Ravi    20000         TCS   20
1  102    Prema    30000       Wipro   21
2  103     Basu    47000   Accenture   22
3  104   Prabhu   100000     Infosys   18

In [ ]:
data.columns

Index([' id', ' Name', ' Salary', ' company', 'Age'], dtype='object')

In [ ]:
data.dtypes

 id          int64
 Name       object
 Salary      int64
 company    object
Age          int64
dtype: object

In [ ]:
data.shape

(4, 5)

In [ ]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
data.head()

    id     Name   Salary     company  Age
0  101     Ravi    20000         TCS   20
1  102    Prema    30000       Wipro   21
2  103     Basu    47000   Accenture   22
3  104   Prabhu   100000     Infosys   18

In [ ]:
data.tail()

    id     Name   Salary     company  Age
0  101     Ravi    20000         TCS   20
1  102    Prema    30000       Wipro   21
2  103     Basu    47000   Accenture   22
3  104   Prabhu   100000     Infosys   18

In [ ]:
data.describe()

               id         Salary        Age
count    4.000000       4.000000   4.000000
mean   102.500000   49250.000000  20.250000
std      1.290994   35621.856586   1.707825
min    101.000000   20000.000000  18.000000
25%    101.750000   27500.000000  19.500000
50%    102.500000   38500.000000  20.500000
75%    103.250000   60250.000000  21.250000
max    104.000000  100000.000000  22.000000

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0    id       4 non-null      int64
 1    Name     4 non-null      object
 2    Salary   4 non-null      int64
 3    company  4 non-null      object
 4   Age       4 non-null      int64
dtypes: int64(3), object(2)
memory usage: 292.0+ bytes

In [ ]:
import pandas as pd
employee={
    'ID':[101,102,103,104],
    'Name':['Rahul','Anita','John','Kiran'],
    'Department':['IT','HR','Sales','IT'],
    'Salary':[50000,45000,60000,55000]}
df= pd.DataFrame(employee)
df

    ID   Name Department  Salary
0  101  Rahul         IT   50000
1  102  Anita         HR   45000
2  103   John      Sales   60000
3  104  Kiran         IT   55000

In [ ]:
print(df['Salary'].mean())

NameError: name 'df' is not defined

In [ ]:
print(df[df['Department']=='IT'])

NameError: name 'df' is not defined

In [ ]:
 import pandas as pd
data=pd.read_excel("/content/Excel.xlsl.xlsx")
data

  Employee       Name    Age  Gender Department  Salary       City
0      E101     Akash   25.0       M         IT   45000  Bengalore
1      E102     Megha    NaN       F         Hr   38000    Chennai
2      E103      John   28.0    Male    Finance   55000        NaN
3       NaN     Kavya  240.0  Female         IT   48000     Mysore
4      E105    Darshi   26.0    Male      Sales   25000  Bengalore
5      E106   Supriya    NaN  Female         HR  -38000    Chennai
6      E107    Darshi   26.0    Male      Sales   25000  Bengalore
7      E108     Sneha   23.0     NaN         IT   47000      Delhi
8      E109       NaN  -27.0  Female    Finance   52000  Hyderabad
9      E110     Vikas   22.0    Male         IT   99999    Chennai

In [ ]:
data.isnull()

   Employee    Name    Age  Gender  Department  Salary   City
0      False  False  False   False       False   False  False
1      False  False   True   False       False   False  False
2      False  False  False   False       False   False   True
3       True  False  False   False       False   False  False
4      False  False  False   False       False   False  False
5      False  False   True   False       False   False  False
6      False  False  False   False       False   False  False
7      False  False  False    True       False   False  False
8      False   True  False   False       False   False  False
9      False  False  False   False       False   False  False